version: "2"
linters:
  enable:
    - revive
    - misspell
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
  exclusions:
    presets:
      - comments
formatters:
  enable:
    - gofmt

