version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: go version
      - run: make setup
      - run: make lint
      - run: make build
      - run: make test
