name: pr-push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Setup Tools
        run: make setup
      - name: Versions
        run: go version && golangci-lint --version
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Test
        run: make test
